import "./globals.css";
import { Inter } from 'next/font/google'; 



export const metadata = {
  title: 'Mini Storefront',
  description: 'Generated by Next.js', 
}; 

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}























